#3. Declara la variable libro, y asígnale el valor “Python”, y muéstralo por pantalla con la frase:
# “Estoy aprendiendo Python gracias a este libro de libro”. 
# Para ello, debes concatenar la primera parte de la frase con el valor que tendrá la variable. 
# Recuerda generar un espacio antes de concatenar la variable al resto del texto.
libro = "Python"
print("Estoy aprendiendo "+ libro +" gracias a este libro de libro")
